### ISSUE TITLE
New npm version

### ISSUE THREAD

**Issue by clusby** [saulhoward/react-evil-icons#9]
Hi,

Could you please push a new version to npm? I just pulled in 0.4.0 and it still has the defunct PropTypes

    propTypes: {
        size: React.PropTypes.string.isRequired,
        name: React.PropTypes.string.isRequired,
        className: React.PropTypes.string },

Cheers

**Comment by saulhoward** [comment]
@clusby thanks for the issue. It looks as if the repository won't build in it's current state -- possibly because dependencies need to be updated. I will look into this when I get a chance, until then PRs are welcome. Once it's building, I can publish the new version.

**Comment by saulhoward** [comment]
0.5.0 is now published to npm
